x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  talker:
    build:
      dockerfile: Dockerfile.chatter
    <<: *common-config
    command: ros2 run demo_nodes_cpp talker

  rosbridge-ws:
    build:
      dockerfile: Dockerfile
      context: ../
    <<: *common-config
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  listener:
    build:
      dockerfile: Dockerfile.webserver
    ports:
      - 8080:8080

